// <auto-generated>
// Code generated by LUISGen CognitiveModel\HospitalInfo.json -cs HospitalInfo.Services.HospitalInfoService -o Services
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace HospitalInfo.Services
{
    public partial class HospitalInfoService: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Cancel, 
            HospitalCaracteristicsFinding, 
            HospitalFinding, 
            InfoCategorie, 
            LocalisationFinding, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Annuler;

            public string[] Categorie;

            public string[] Hopital;
            public string[] Nom_Hopital;

            public string[] Localisation;

            public string[] Province;

            public string[] Region;

            public string[] Signification;

            public string[] Ville;

            // Composites
            public class _InstanceCaracteristique
            {
                public InstanceData[] Hopital;
                public InstanceData[] Province;
                public InstanceData[] Ville;
                public InstanceData[] Region;
                public InstanceData[] Categorie;
            }
            public class CaracteristiqueClass
            {
                public string[] Hopital;
                public string[] Province;
                public string[] Ville;
                public string[] Region;
                public string[] Categorie;
                [JsonProperty("$instance")]
                public _InstanceCaracteristique _instance;
            }
            public CaracteristiqueClass[] Caracteristique;

            // Instance
            public class _Instance
            {
                public InstanceData[] Annuler;
                public InstanceData[] Caracteristique;
                public InstanceData[] Recherche_de_la_Catégorie;
                public InstanceData[] Tous_les_caractéristiques;
                public InstanceData[] Categorie;
                public InstanceData[] Hopital;
                public InstanceData[] Nom_Hopital;
                public InstanceData[] Localisation;
                public InstanceData[] Province;
                public InstanceData[] Region;
                public InstanceData[] Signification;
                public InstanceData[] Ville;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<HospitalInfoService>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
